user:
    resource: "@UserBundle/Resources/config/routing.yml"
    prefix:   /

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

search:
    resource: "@SearchBundle/Resources/config/routing.yml"
    prefix:   /

common:
    resource: "@CommonBundle/Resources/config/routing.yml"
    prefix:   /

advert:
    resource: "@AdvertBundle/Resources/config/routing.yml"
    prefix:   /
