common:
    resource: "@CommonBundle/Resources/config/routing.yml"
    prefix:   /

advert:
    resource: "@AdvertBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: "@AppBundle/Resources/config/routing.yml"
    prefix:   /
