
advert_add_page:
    path:   /advert/add
    defaults: { _controller: AdvertBundle:Advert:index }

advert_edit_page:
    path:     /advert/{id}/edit
    defaults: { _controller: AdvertBundle:Advert:index }

advert_detail_page:
    path:     /advert/{slug}
    defaults: { _controller: AdvertBundle:Detail:index }

get_model_by_make:
  path: /make/models
  defaults: { _controller: AdvertBundle:Advert:getModelsByMake }
