advert_homepage:
    path:     /advert
    defaults: { _controller: AdvertBundle:Default:index }

advert_add_page:
    path:   /advert/add
    defaults: { _controller: AdvertBundle:Default:add }

advert_detail:
    path:     /advert/{id}
    defaults: { _controller: AdvertBundle:Default:detail }
