
advert_add_page:
    path:   /advert/add
    defaults: { _controller: AdvertBundle:Advert:add }

advert_detail_page:
    path:     /advert/{id}
    defaults: { _controller: AdvertBundle:Detail:index }

advert_edit_page:
    path:     /advert/{id}/edit
    defaults: { _controller: AdvertBundle:Advert:edit }
