search_homepage:
    path:     /
    defaults: { _controller: SearchBundle:Search:index }

search_adverts_homepage:
    path:     /search/adverts
    defaults: { _controller: SearchBundle:Search:getAdverts }
